services:
  db:
    image: postgres:16
    container_name: turtleshop-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - turtleshop_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:latest
    container_name: turtleshop-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: turtleshop
    ports:
      - "27017:27017"
    volumes:
      - ./backend/turtleshop-api/src/main/resources/db/mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: mongosh --quiet --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 5s
      retries: 5
    
  mongo-express:
    image: mongo-express
    container_name: turtleshop-mongo-gui
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_USER}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy

  api:
    build:
      context: ./backend/turtleshop-api
      dockerfile: Dockerfile
      target: dev
    container_name: turtleshop-api
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/turtleshop?authSource=admin
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/turtleshop-api:/app
      - /app/.gradle
      - /app/build

  frontend:
    build:
      context: ./frontend/turtleshop-web
      dockerfile: Dockerfile
    container_name: turtleshop-frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./frontend/turtleshop-web:/app
      - /app/node_modules

volumes:
  turtleshop_pgdata:
  turtleshop_mongodb_data: