@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkB0dXJ0bGVzaG9wLm9yZyIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaWF0IjoxNzc5Nzc5MzUwLCJleHAiOjE3Nzk3ODI5NTB9.onESNNS1E9PR9RohRfxM_phfCvmPQJ55eA-jobwTU9E
@id = b299567a-c2fb-49bc-94ad-31c9a7cfce99
@wId = 14
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@turtleshop.org",
  "password": "splinter"
}

### Get all wishlists
GET http://localhost:8080/api/wishlist
Authorization: Bearer {{token}}

### Get wishlist by id
GET http://localhost:8080/api/wishlist/{{wId}}
Authorization: Bearer {{token}}

### Get wishlist by customer id
GET http://localhost:8080/api/wishlist/customer/{{id}}
Authorization: Bearer {{token}}

### Create a wishlist for a customer
POST http://localhost:8080/api/wishlist/customer/{{id}}
Authorization: Bearer {{token}}

### Delete a wishlist by id
DELETE http://localhost:8080/api/wishlist/{{wId}}
Authorization: Bearer {{token}}