### Login as admin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@turtleshop.org",
  "password": "splinter"
}

### Get all wishlists
GET http://localhost:8080/api/wishlist
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkB0dXJ0bGVzaG9wLm9yZyIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaWF0IjoxNzc4MDEwMTgxLCJleHAiOjE3NzgwMTM3ODF9.ohO3-oRl21UPSweearOgAQn2KULnbASKwwfu5g1vXo4