@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkB0dXJ0bGVzaG9wLm9yZyIsInJvbGVzIjpbIlJPTEVfQURNSU4iLCJST0xFX1VTRVIiXSwiaWF0IjoxNzc5Mjc2NjU2LCJleHAiOjE3NzkyODAyNTZ9.5OP4zZOJ13OYhXg4tCvwZRpEYo4J6eYPNyyVgLrX-IU
@wishlistItemId = 1
@wishlistId = 14
@productId = 3
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "admin@turtleshop.org",
  "password": "splinter"
}

> {% client.global.set("token", response.body.token) %}

### Get all wishlist items
GET http://localhost:8080/api/wishlist-item
Authorization: Bearer {{token}}

### Get wishlist item by id
GET http://localhost:8080/api/wishlist-item/{{wishlistItemId}}
Authorization: Bearer {{token}}

### Get wishlist items by wishlist id
GET http://localhost:8080/api/wishlist-item/wishlist/{{wishlistId}}
Authorization: Bearer {{token}}

### Get wishlist item by product id
GET http://localhost:8080/api/wishlist-item/product/{{productId}}
Authorization: Bearer {{token}}

### Create a wishlist item
POST http://localhost:8080/api/wishlist-item/wishlist/{{wishlistId}}/product/{{productId}}
Authorization: Bearer {{token}}

### Create a wishlist item and return id
POST http://localhost:8080/api/wishlist-item/wishlist/{{wishlistId}}/product/{{productId}}/return-id
Authorization: Bearer {{token}}

### Update a wishlist item
PUT http://localhost:8080/api/wishlist-item
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "wishlistItemId": {{wishlistItemId}},
  "wishlistId": {{wishlistId}},
  "productId": {{productId}}
}

### Delete wishlist item by id
DELETE http://localhost:8080/api/wishlist-item/{{wishlistItemId}}
Authorization: Bearer {{token}}

### Delete all items by wishlist id
DELETE http://localhost:8080/api/wishlist-item/wishlist/{{wishlistId}}
Authorization: Bearer {{token}}

### Delete item from wishlist
DELETE http://localhost:8080/api/wishlist-item/wishlist/{{wishlistId}}/product/{{productId}}
Authorization: Bearer {{token}}