ALTER TABLE CUSTOMER ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS customer_self_view ON CUSTOMER
    FOR SELECT
    TO PUBLIC
    USING (customer_id = current_setting('customer_id')::UUID);

ALTER TABLE CUSTOMER FORCE ROW LEVEL SECURITY;

