ALTER TABLE ORDERS ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS customer_self_view ON ORDERS
    FOR SELECT
    TO PUBLIC
    USING (customer_id = current_setting('customer_id')::UUID);

ALTER TABLE ORDERS FORCE ROW LEVEL SECURITY;

